#!/usr/bin/env perl

#---| Shelling for examples/test.gravity -> ./test
#---| Creates a "virtual" environment to handle variables in
#---| Attempts to catch any errors that may not have been caught preivously

our %STACK = ();
our %REGISTERS = (
    sra => 0,
    srb => 0,
    src => 0,
    srd => 0,
    sre => 0,
);
our $WARN = 0;

sub store {
    my $variable = $_[0];
    my $data = $_[1];
    $STACK{$variable} = $data;
}

sub setRegister {
    my $register = $_[0];
    my $value = $_[1];

    if (!exists $REGISTERS{$register}) {
        print "<FATAL-Error>\n|> Reason: Invalid register location: " . $register . "\n";
        die;
    }

    $REGISTERS{$register} = $value;
}

sub moveRegister {
    my $register = $_[0];
    my $memory_location = $_[1];
    $STACK{$memory_location} = $REGISTERS{$register};
}

sub getRegister {
    my $register = $_[0];
    if (!exists $REGISTERS{$register}) {
        print "<FATAL-Error>\n|> Reason: Invalid register location: " . $register . "\n";
        die;
    }
    return $REGISTERS{$register};
}

sub puts {
    my $d0 = $_[0];
    if (exists $STACK{$d0}) {
        print $STACK{$d0};
    } else {
        print $d0;
    }
}

sub update {
    my $d0 = $_[0];
    my $d1 = $_[1];

    if (exists $STACK{$d1}) {
        $d1 = $STACK{$d1};
    }

    if (length($d0) > 2) {
        if (!exists $REGISTERS{$d0}) {
            print "<FATAL-Error>\n|> Reason: Invalid register location: " . $d0 . "\n";
            die;
        }
        &setRegister($d0, $d1);
    } else {
        if (!exists $STACK{$d0}) {
            if ($WARN == 1) {
                print "Attempt to assign value to uninitalized data point: " . $d0 . "\n";
            }
            &store($d0, $d1);
        }
        &store($d0, $d1);
    }
}

sub add {
    my $d0 = $_[0];
    my $d1 = $_[1];
    my $register = $_[2];
    &setRegister($register, $d0 + $d1);
}

sub subt {
    my $d0 = $_[0];
    my $d1 = $_[1];
    my $register = $_[2];
    &setRegister($register, $d0 - $d1);
}

sub mul {
    my $d0 = $_[0];
    my $d1 = $_[1];
    my $register = $_[2];
    &setRegister($register, $d0 * $d1);
}

sub div {
    my $d0 = $_[0];
    my $d1 = $_[1];
    my $register = $_[2];
    &setRegister($register, $d0 / $d1);
}

sub exp {
    my $d0 = $_[0];
    my $d1 = $_[1];
    my $register = $_[2];
    &setRegister($register, $d0 ** $d1);
}

sub read {
    my $d0 = $_[0];
    my $stdin = <STDIN>;
    chomp $stdin;
    &store($d0, $stdin);
}

sub compare {
    my $d0 = $_[0];
    my $d1 = $_[1];
    my $d2 = $_[2];

    if (length($d0) > 3) {
        $d0 = $STACK{$d0};
    } else {
        print "WIP";
    }

    if (length($d1) > 3) {
        $d1 = $STACK{$d1};
    } else {
        print "WIP";
    }

    if ($d0 eq $d1) {
        &setRegister($d2, 0);
    } else {
        &setRegister($d2, 1);
    }
}

#---| File: examples/guessing_game.gravity
sub _begin {
    &store("L02_gravityV", 100);
    &store("L03_gravityV", "Girlfriend");
    &store("L04_gravityV", 0);
    &store("L05_gravityV", 5);
    &store("L06_gravityV", "QUIT");
    &store("L07_gravityV", "Quit");
    &store("L08_gravityV", "quit");
    &store("L09_gravityV", "nice");
    &store("L10_gravityV", "bruh");
    &store("L11_gravityV", "BRUH");
    &store("L12_gravityV", "Bruh");
    &store("L04_gravityV", 1);


    lblDo_AGAIN:
    &puts("Enter the correct name: ");
    &read("L01_gravityV");
    &compare("L01_gravityV", "L06_gravityV", "sra");
    goto lblQUIT if ($REGISTERS{"sra"} == 0);
    &compare("L01_gravityV", "L07_gravityV", "sra");
    goto lblQUIT if ($REGISTERS{"sra"} == 0);
    &compare("L01_gravityV", "L08_gravityV", "sra");
    goto lblQUIT if ($REGISTERS{"sra"} == 0);
    &compare("L01_gravityV", "L10_gravityV", "sra");
    goto lblbruh if ($REGISTERS{"sra"} == 0);
    &compare("L01_gravityV", "L11_gravityV", "sra");
    goto lblbruh if ($REGISTERS{"sra"} == 0);
    &compare("L01_gravityV", "L12_gravityV", "sra");
    goto lblbruh if ($REGISTERS{"sra"} == 0);
    &compare("L01_gravityV", "L09_gravityV", "sra");
    goto lblnice if ($REGISTERS{"sra"} == 0);
    &compare("L03_gravityV", "L01_gravityV", "sra");
    goto lblWRONG if ($REGISTERS{"sra"} != 0);
    &puts("Hello ");
    &puts("\033[32m");
    &puts("L01_gravityV");
    &puts("\033[0m!");
    &puts("\n");
    &puts("\n");
    &puts("-------------------------------\n");
    &puts("Congraulations on guessing the correct name!\n");
    &puts("Your prize is....NOTHINGGGG :D\n");
    exit 0;

    lblWRONG:
    &puts("Incorrect Name: ");
    &puts("\033[91m");
    &puts("L01_gravityV");
    &puts("\033[0m\n");
    &add("L04_gravityV", 1, "sra");
    &store("L04_gravityV", &getRegister("sra"));
    &compare("L04_gravityV", "L05_gravityV", "sra");
    goto lblHINT if ($REGISTERS{"sra"} == 0);
    goto lblDo_AGAIN;

    lblHINT:
    &puts("Hint: Its the nickname of the creator of gravity :)");
    goto lblDo_AGAIN;

    lblQUIT:
    &puts("Okay :)\n");
    exit 69;

    lblnice:
    &puts("I know right\n");
    goto lblDo_AGAIN;

    lblbruh:
    &puts("I'M SORRYYYYYY ;-;\n");
    goto lblDo_AGAIN;

}
&_begin();
